#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-IPC-Run
Version  : 20180523.0
Release  : 24
URL      : https://cpan.metacpan.org/authors/id/T/TO/TODDR/IPC-Run-20180523.0.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TODDR/IPC-Run-20180523.0.tar.gz
Summary  : 'system() and background procs w/ piping, redirs, ptys (Unix, Win32)'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-2.0
Requires: perl-IPC-Run-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
IPC::Run - system() and background procs w/ piping, redirs, ptys (Unix,
Win32)

%package dev
Summary: dev components for the perl-IPC-Run package.
Group: Development
Provides: perl-IPC-Run-devel = %{version}-%{release}

%description dev
dev components for the perl-IPC-Run package.


%package license
Summary: license components for the perl-IPC-Run package.
Group: Default

%description license
license components for the perl-IPC-Run package.


%prep
%setup -q -n IPC-Run-20180523.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-IPC-Run
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-IPC-Run/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1IPC/Run.pm
/usr/lib/perl5/vendor_perl/5.28.1IPC/Run/Debug.pm
/usr/lib/perl5/vendor_perl/5.28.1IPC/Run/IO.pm
/usr/lib/perl5/vendor_perl/5.28.1IPC/Run/Timer.pm
/usr/lib/perl5/vendor_perl/5.28.1IPC/Run/Win32Helper.pm
/usr/lib/perl5/vendor_perl/5.28.1IPC/Run/Win32IO.pm
/usr/lib/perl5/vendor_perl/5.28.1IPC/Run/Win32Pump.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/IPC::Run.3
/usr/share/man/man3/IPC::Run::Debug.3
/usr/share/man/man3/IPC::Run::IO.3
/usr/share/man/man3/IPC::Run::Timer.3
/usr/share/man/man3/IPC::Run::Win32Helper.3
/usr/share/man/man3/IPC::Run::Win32IO.3
/usr/share/man/man3/IPC::Run::Win32Pump.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-IPC-Run/LICENSE
